#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5332/customer
#    username: peterhamz
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
#  main:
#    web-application-type: servlet

server:
  port: 8082

spring:
  profiles:
    active: qa
---

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customer
    password: jamespeter16
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  config:
    activate:
      on-profile: dev
welcome:
  message: Some Configuration Data


---
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customer_prod
    password: jamespeter16
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: Some Configuration Data

---
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/customer_qa
    password: jamespeter16
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Some Configuration Data

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "the endpoint to be excluded"